kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: "go-build" 
spec:
  runPolicy: "Serial"
  triggers: 
    -
      type: "GitHub"
      github:
        secret: "XErdUZvclqfa-FYk3fIm"
    - type: "Generic"
      generic:
        secret: "8xwmTWbV4n8PwnXzNmp_"
    -
      type: "ImageChange"
  source: 
    git:
      uri: "https://github.com/VikneshSuresh/TestRepo"
  strategy:
    dockerStrategy:
      dockerfilePath: Dockerfile
  output: 
    to:
      kind: "DockerImage"
      name: "10.168.0.76:9000/repository/dev-registry/go:1.0"
    pushSecret:
      name: "nexus-secret"
      